using System.Diagnostics;
using static LocalPlaylistMaster.Backend.MetadataFillerExtensions;

namespace LocalPlaylistMaster.Backend.Metadata_Fillers
{
    /// <summary>
    /// Auto generated by YT
    /// </summary>
    public class ProvidedMetadata : MetadataBase
    {
        public override string Name => "Provided by YT";

        public override string ConfigName => "Provided";

        /*
         * Provided to YouTube by INSERTCOMPANYHERE
         * 
         * Title · Artist
         * 
         * Album
         * 
         * ℗
         * 
         * Released on: YYYY-MM-DD
         * 
         * ...
         * 
         * Auto-generated by YouTube.
         */

        public override bool Fill(Track track, out Track modified)
        {
            modified = new Track(track);

            if (track.Description.Contains("Provided to YouTube by"))
            {
                string[] lines = LineifyDescription(track.Description);
                Debug.Assert(lines[0].Contains("Provided to YouTube by"));

                string[] performers = lines[1].Split('·')[1..];
                for (int i = 0; i < performers.Length; i++)
                {
                    performers[i] = performers[i].Trim();
                }

                modified.Artists = string.Join(", ", performers);
                modified.Album = lines[2].Trim();

                return true;
            }

            return false;
        }
    }
}
