name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Auto Version
        id: set-version
        run: python autoversion.py
      
      - name: State Version
        run:  echo ${{ env.MY_VERSION }}

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-version: 'latest'
          
      - name: Restore NuGet Packages
        run: nuget restore LocalPlaylistMaster.sln
        
      - name: Build Solution
        run: msbuild /p:Configuration=Release LocalPlaylistMaster.sln
        
      - name: Upload Msi
        id: upload-msi
        uses: actions/upload-artifact@v4
        with:
          name: installer.msi
          path: Installer/bin/x64/Release/Installer.msi

      - name: Create Release
        id: create-release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.MY_VERSION }}
          release_name: ${{ env.MY_VERSION_NAME }}
          files: Installer/bin/x64/Release/Installer.msi
